language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - 12

script:
  - npm test
#  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
#  - ./tools/continuous-deployment.travis.sh

after_script:
  - node node_modules/.bin/codecov
